/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package questao1.poolistas9;

import java.util.Collections;
import java.util.Comparator;

/**
 *
 * @author User
 */
public class DadosTurma extends javax.swing.JDialog {

    /**
     * Creates new form NewJDialog
     */
    static String texto1;
    static Turma turma;
    
    public DadosTurma(java.awt.Frame parent, boolean modal, String texto1, Turma turma) {
        super(parent, modal);
        initComponents();
        this.texto1 = texto1;
        this.turma = turma;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        Listar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        NOME = new javax.swing.JRadioButton();
        MATRICULA = new javax.swing.JRadioButton();
        NOTA = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        CRESCENTE = new javax.swing.JRadioButton();
        DECRESCENTE = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        Listar.setText("Listar");
        Listar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListarActionPerformed(evt);
            }
        });

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        buttonGroup1.add(NOME);
        NOME.setText("Nome");
        NOME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NOMEActionPerformed(evt);
            }
        });

        buttonGroup1.add(MATRICULA);
        MATRICULA.setText("Matricula");

        buttonGroup1.add(NOTA);
        NOTA.setText("Nota");
        NOTA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NOTAActionPerformed(evt);
            }
        });

        jLabel1.setText("Ordenar Por:");

        buttonGroup2.add(CRESCENTE);
        CRESCENTE.setText("Crescente");

        buttonGroup2.add(DECRESCENTE);
        DECRESCENTE.setText("Decrescente");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(NOME)
                .addGap(18, 18, 18)
                .addComponent(MATRICULA)
                .addGap(18, 18, 18)
                .addComponent(NOTA)
                .addGap(44, 44, 44))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(CRESCENTE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(DECRESCENTE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Listar)
                        .addGap(93, 93, 93))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                        .addContainerGap())))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(318, Short.MAX_VALUE)
                    .addComponent(jButton2)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NOME)
                    .addComponent(MATRICULA)
                    .addComponent(NOTA)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Listar)
                    .addComponent(CRESCENTE)
                    .addComponent(DECRESCENTE))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(302, Short.MAX_VALUE)
                    .addComponent(jButton2)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void setTexto(String text) {
        jTextArea1.setText(text);
    }
    
    private void ListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListarActionPerformed
 
        int tipo = 0;
        if (DECRESCENTE.isSelected()) {
            tipo = 1;
        }

        if (MATRICULA.isSelected()) {
            if (tipo == 1) {
                Collections.sort(turma.getAlunos(), Collections.reverseOrder(new OrdenarMatricula()));
            } else {
                Collections.sort(turma.getAlunos(), new OrdenarMatricula());
            }
        } else if (NOTA.isSelected()) {
            if (tipo == 1) {
                Collections.sort(turma.getAlunos(), Collections.reverseOrder(new OrdenarNota()));
            } else {
                Collections.sort(turma.getAlunos(), new OrdenarNota());
            }
        } else if (NOME.isSelected()) {
            if (tipo == 1) {
                Collections.sort(turma.getAlunos(), Collections.reverseOrder(new OrdenarNome()));
            } else {
                Collections.sort(turma.getAlunos(), new OrdenarNome());
            }
        }
        
        
        String textoTurma = "";
        
        for (int i = 0; i < turma.getSize(); i++) {
            textoTurma += turma.getAlunos().get(i).getNome() + " "
                    + turma.getAlunos().get(i).getMatricula() + " - Nota ENEM: "
                    + turma.getAlunos().get(i).getNota() + "\n";
        }

        textoTurma += "Aluno(a) com melhor nota: "
                + turma.obterAlunoMelhorNotaEnem().getNome() + " - "
                + turma.obterAlunoMelhorNotaEnem().getNota();
        
        setTexto(texto1 + textoTurma);
        
    }//GEN-LAST:event_ListarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void NOMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NOMEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NOMEActionPerformed

    private void NOTAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NOTAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NOTAActionPerformed


    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DadosTurma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DadosTurma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DadosTurma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DadosTurma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DadosTurma dialog = new DadosTurma(new javax.swing.JFrame(), true, texto1, turma);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton CRESCENTE;
    private javax.swing.JRadioButton DECRESCENTE;
    private javax.swing.JButton Listar;
    private javax.swing.JRadioButton MATRICULA;
    private javax.swing.JRadioButton NOME;
    private javax.swing.JRadioButton NOTA;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
