/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package camada1.pooListas7;

import camada2.poolistas7.Ponto;
import camada2.poolistas7.Retangulo;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        r1EsqSupX = new javax.swing.JTextField();
        r1EsqSupY = new javax.swing.JTextField();
        r1DirInfX = new javax.swing.JTextField();
        r1DirInfY = new javax.swing.JTextField();
        r2EsqSupX = new javax.swing.JTextField();
        r2EsqSupY = new javax.swing.JTextField();
        r2DirInfY = new javax.swing.JTextField();
        r2DirInfX = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        r3EsqSupX = new javax.swing.JTextField();
        r3EsqSupY = new javax.swing.JTextField();
        r3DirInfX = new javax.swing.JTextField();
        r3DirInfY = new javax.swing.JTextField();
        jBtn1 = new javax.swing.JButton();
        jBtn2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 204, 204));

        jLabel1.setText("Retângulo 1:");

        jLabel2.setText("Retângulo 2:");

        jLabel3.setText("Ponto Superior Esquerdo");

        jLabel4.setText("Ponto Inferior Direito");

        jLabel5.setText("X");

        jLabel6.setText("X");

        jLabel7.setText("Y");

        jLabel8.setText("Y");

        r1EsqSupY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r1EsqSupYActionPerformed(evt);
            }
        });

        r1DirInfX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r1DirInfXActionPerformed(evt);
            }
        });

        r1DirInfY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r1DirInfYActionPerformed(evt);
            }
        });

        r2EsqSupX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r2EsqSupXActionPerformed(evt);
            }
        });

        r2EsqSupY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r2EsqSupYActionPerformed(evt);
            }
        });

        r2DirInfY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r2DirInfYActionPerformed(evt);
            }
        });

        r2DirInfX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r2DirInfXActionPerformed(evt);
            }
        });

        jLabel9.setText("Novo Retângulo:");

        r3EsqSupX.setEnabled(false);
        r3EsqSupX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r3EsqSupXActionPerformed(evt);
            }
        });

        r3EsqSupY.setEnabled(false);
        r3EsqSupY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r3EsqSupYActionPerformed(evt);
            }
        });

        r3DirInfX.setEnabled(false);
        r3DirInfX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r3DirInfXActionPerformed(evt);
            }
        });

        r3DirInfY.setEnabled(false);
        r3DirInfY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r3DirInfYActionPerformed(evt);
            }
        });

        jBtn1.setText("Calcular");
        jBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn1ActionPerformed(evt);
            }
        });

        jBtn2.setText("Limpar");
        jBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel9)
                        .addGap(157, 157, 157))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(112, 112, 112)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(65, 65, 65)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(r1EsqSupX, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(r1EsqSupY, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(80, 80, 80)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(r3EsqSupX, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(r3EsqSupY, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(r2EsqSupX, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(r2EsqSupY, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                        .addGap(10, 10, 10)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(r1DirInfX, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(r1DirInfY, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(r3DirInfX, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(r2DirInfX, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(r2DirInfY, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(r3DirInfY, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(112, 112, 112))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(128, 128, 128))
            .addGroup(layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addComponent(jBtn1)
                .addGap(95, 95, 95)
                .addComponent(jBtn2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(r1EsqSupX, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(r1EsqSupY, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(r1DirInfX, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(r1DirInfY, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(r2EsqSupX, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(r2EsqSupY, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(r2DirInfY, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(r2DirInfX, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtn1)
                    .addComponent(jBtn2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(r3EsqSupX, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(r3EsqSupY, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(r3DirInfX, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(r3DirInfY, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void r1EsqSupYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r1EsqSupYActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r1EsqSupYActionPerformed

    private void r1DirInfXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r1DirInfXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r1DirInfXActionPerformed

    private void r1DirInfYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r1DirInfYActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r1DirInfYActionPerformed

    private void r2EsqSupXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r2EsqSupXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r2EsqSupXActionPerformed

    private void r2EsqSupYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r2EsqSupYActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r2EsqSupYActionPerformed

    private void r2DirInfYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r2DirInfYActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r2DirInfYActionPerformed

    private void r2DirInfXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r2DirInfXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r2DirInfXActionPerformed

    private void r3EsqSupXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r3EsqSupXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r3EsqSupXActionPerformed

    private void r3EsqSupYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r3EsqSupYActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r3EsqSupYActionPerformed

    private void r3DirInfXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r3DirInfXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r3DirInfXActionPerformed

    private void r3DirInfYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r3DirInfYActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r3DirInfYActionPerformed

    private void jBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn2ActionPerformed
        r1EsqSupX.setText("");
        r1DirInfX.setText("");
        r2EsqSupX.setText("");
        r2DirInfX.setText("");
        r3EsqSupX.setText("");
        r3DirInfX.setText("");
        r1EsqSupY.setText("");
        r1DirInfY.setText("");
        r2EsqSupY.setText("");
        r2DirInfY.setText("");
        r3EsqSupY.setText("");
        r3DirInfY.setText("");
    }//GEN-LAST:event_jBtn2ActionPerformed

    private void jBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn1ActionPerformed

        try {
            Ponto p1 = new Ponto(Integer.parseInt(r1EsqSupX.getText()), Integer.parseInt(r1EsqSupY.getText()));
            Ponto p2 = new Ponto(Integer.parseInt(r1DirInfX.getText()), Integer.parseInt(r1DirInfY.getText()));
            Retangulo r1 = new Retangulo();
            r1.setPontoDireitoInf(p2);
            r1.setPontoEsquerdoSup(p1);
            Ponto p3 = new Ponto(Integer.parseInt(r2EsqSupX.getText()), Integer.parseInt(r2EsqSupY.getText()));
            Ponto p4 = new Ponto(Integer.parseInt(r2DirInfX.getText()), Integer.parseInt(r2DirInfY.getText()));
            Retangulo r2 = new Retangulo();
            r2.setPontoDireitoInf(p4);
            r2.setPontoEsquerdoSup(p3);

            Retangulo resultado = r1.calcularInterseccao(r2);

            r3EsqSupX.setText(String.valueOf(resultado.getPontoEsquerdoSup().getX()));
            r3EsqSupY.setText(String.valueOf(resultado.getPontoEsquerdoSup().getY()));
            r3DirInfX.setText(String.valueOf(resultado.getPontoDireitoInf().getX()));
            r3DirInfY.setText(String.valueOf(resultado.getPontoDireitoInf().getY()));
        } catch (IllegalArgumentException e) {
           JOptionPane.showMessageDialog(null, e.getMessage());
       }
    }//GEN-LAST:event_jBtn1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtn1;
    private javax.swing.JButton jBtn2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField r1DirInfX;
    private javax.swing.JTextField r1DirInfY;
    private javax.swing.JTextField r1EsqSupX;
    private javax.swing.JTextField r1EsqSupY;
    private javax.swing.JTextField r2DirInfX;
    private javax.swing.JTextField r2DirInfY;
    private javax.swing.JTextField r2EsqSupX;
    private javax.swing.JTextField r2EsqSupY;
    private javax.swing.JTextField r3DirInfX;
    private javax.swing.JTextField r3DirInfY;
    private javax.swing.JTextField r3EsqSupX;
    private javax.swing.JTextField r3EsqSupY;
    // End of variables declaration//GEN-END:variables
}
